var GAME_LEVELS = [ 
  //0
  ["                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              ",
   "     xx  xx  xxxx  xx   xx    ",
   "     xx  xx xxxxxx xx   xx    ",
   "     xx  xx xx  xx xx   xx    ",
   "     xxxxxx xx  xx xx   xx    ",
   "      xxxxx xx  xx xx   xx    ",
   "         xx xx  xx xx   xx    ",
   "      xxxxx xxxxxx xxx xxx    ",
   "      xxxxx  xxxx   xxxxx     ",
   "                              ",
   " xx      xxxx  xxxxxxx xxxxxx ",
   " xx     xx  xx xx   xx xxxxxx ",
   " xx     xx  xx  xx     xx     ",
   " xx     xx  xx   xx    xxxxxx ",
   " xx     xx  xx    xx   xxxxxx ",
   " xx     xx  xx     xx  xx     ",
   " xxxxxx xx  xx xx   xx xxxxxx ",
   " xxxxxx  xxxx  xxxxxxx xxxxxx ",
   "                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              "],
  //1
  ["                                                             ",
   " xx xxx x  x  xx xx xxx  xxx x x xx  xx xxx xxx xxx x xxx    ",                                                                                                                                                                                                                                                                     
   " x  x x x  x  x  x   x    x  x x x   x  x x  x  x x x x      ",                                                                                                                                                                                                                                                                      
   " x  x x x  x  xx x   x    x  xxx xx  x  x x  x  x x x  x     ",                                                                                                                                                                                                                                                                            
   " x  x x x  x  x  x   x    x  x x x   x  x x  x  x x x   x    ",                                                                                                                                                                                                                                                                           
   " xx xxx xx xx xx xx  x    x  x x xx  xx xxx xxx x xxx xxx x  ",
   "                                                             ",
   "                                                             ",
   "                                                             ",
   "                                                 o           ",
   "                                                             ",
   "                              x             x                ",
   "                              x o                            ",
   "                              xxxxx                       o  ",
   "                       x                             xxxxxxxx",
   "                                       x                     ",
   "                  o                                          ",
   "                                                             ",
   "         o                        o                       o  ",
   "  @                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                             "],
   //2
  ["                                                             ",
   "        !!!  !!! !!! ! ! !!!   !!! !!! ! ! !! ! ! !          ",                                                                                                                                                                                                                                                                     
   "        !  ! ! ! ! ! ! !  !     !  ! ! ! ! !  ! ! !          ",                                                                                                                                                                                                                                                                      
   "        !  ! ! ! ! ! !    !     !  ! ! ! ! !  !!! !          ",                                                                                                                                                                                                                                                                            
   "        !  ! ! ! ! ! !    !     !  ! ! ! ! !  ! !            ",                                                                                                                                                                                                                                                                           
   "        !!!  !!! ! !!!    !     !  !!! !!! !! ! ! !          ",
   "                                                             ",
   "                                                             ",
   "                                                             ",
   "                                                             ",
   "                               x                             ",
   "                              <x>                            ",
   "                              <x>                            ",
   "                              <x>                            ",
   "                              <x>                            ",
   "                   o          <x>         o                  ",
   "                   x          <x>         x                  ",
   "                                                             ",
   "              x         x            x         x          o  ",
   "  @         xxx!!!!!!!!!xxx    &   xxx!!!!!!!!!xxx           ",
   "xxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   //3
  ["                                                                                                                                                                                                                                                                                                                                                                                     ",
   "																									     																																																																		     ",
   "																								     																																																																			     ",
   "																							     																																																																				     ",
   "                                                                                                                                                                                                                                                                                                                                                                   					 ",
   "                                                                                                                                                                                                                                                                                                                                                x		 					         ",
   "                                                                                                                                                                                                                                                                                                                                                xxx 	                             ",
   "                                o                                                                                                                                                                                                                                                                                                               x  xx         				         ",		  
   "                                x                                                                                                                                                     o          o                                                                                                                                              x    x            					 ",
   "                                                                                                                                              o                     o             xxxxx       xxxxxxx                                                                                                                            xx           * x  xx              	                 ",
   "                                                                                                                         xxxxxxxxxx       xxxxx                     x                                                                                                                                                          xxxx             xxx         xx  xx  xx                ",
   "                                                                                                                                                                                                                                                                                                                             xxxxxx             x           xxxxxxxxxx                ",
   "                         o             o                                                                                                                                                                                                                                                                                   xxxxxxxx             x           xx  xx  xx                ",
   "                         x    xxxxx    x                                                                                                      o          o      o   o   o                                                                                                                     o                          xxxxxxxxxx             x       xx  xx  xx  xx  xx            ",
   "                                                                         xxxx           xxxx                        xxxxx                     x        xxx      x   x   x     x                  xxxx              xx     xx                           xx     xx                          xxxxxxx                      xxxxxxxxxxxx             x       xx  xxxx  xxxx  xx            ",
   "                                                             xxxx         xx             xx                                                                                                                      xxxx     xxxx                       xxxx     xxxx                                                   xxxxxxxxxxxxxx             x   	   xxxxxxxxxxxxxxxxxx         ",
   "                                                 xxxx         xx          xx             xx                                                                                                                    xxxxxx     xxxxxx                   xxxxxx     xxxxxx           xxxx                         xxxx   xxxxxxxxxxxxxxxx             x    o  xxxxxxxx  xxxxxxxx            ",
   "                                                  xx          xx          xx      *      xx                                                                                                                  xxxxxxxx     xxxxxxxx               xxxxxxxx     xxxxxxxx          xx                           xx  xxxxxxxxxxxxxxxxxx                     xxxxxxx    xxxxxxx            ",
   "    @                               &             xx&         xx         &xx      &      xx                                                                                                                xxxxxxxxxx!!!!!xxxxxxxxxx     &     xxxxxxxxxx!!!!!xxxxxxxxxx        xx &                 &       xxxxxxxxxxxxxxxxxxxxxx                     xxxxxxx    xxxxxxx            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                                                                                                                                                                                                                                                                                      "],

  //4
  ["                              <x                          x       x          <x>                 ",
   "                              <x o           o         *  x   o   x          <x>              o  ",
   "                      *       <x     x                    x              o   <x>                 ",
   "xxxxxx                        <xxxx  x      xxx        xxxx                  <x>           xxxxxx",
   "                   xxxxxxx    <x>    x              o  x>                    <x>            vvvvv",
   "                              <x>                      x>                    <x>                 ",
   "                              <x>    xxxxxxx      xxxxxx>         x          <x>                 ",
   "       xxxxxxx                <x>     vvvvv                      <x          <x>              o  ",
   "                      o       <x>                                <x o         x                  ",
   "                               x                                 <x                    xxxxxxxxxx",
   "                   xxxxxxx           xxxxxxx      xxxxxx         <xxxx                  vvvvvvvvv",
   "                    vvvvv             vvvvv            x                                         ",
   "        o                                              x    o                                    ",
   "        x                      x              o        x    x         x       x                  ",
   "       xxx                    <x>                      x                     <x>                 ",
   "     xxxxxxx            o     <x>   o                  x          x     o    <x>     o        ~~~",
   "   xxxxxxxxxxx  &             <x> &       x^^^^^^^^x   x^^^^^^^^^^x   &      <x>              ~~@",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                            "],
   //5
  ["                              ",
   "                              ",
   "                      o       ",
   "                  xxxxxxxx    ",
   "        o                     ",
   "        x                     ",
   "                              ",
   "                              ",
   "    o                         ",
   "    x                         ",
   "                              ",
   "         xxxx                 ",
   "            x  o              ",
   "            x                 ",
   "            xxxxxx            ",
   "     *           x            ",
   "     x           x            ",
   "                 xxxxx        ",
   "                              ",
   "                              ",
   "                              ",
   "   x &     x              xxxx",
   "   xxxxxxxxx           o  x   ",
   "                          x   ",
   "                     xxxxxx   ",
   "                     x        ",
   "                     x        ",
   "                  xxxx        ",
   "                              ",
   "                              ",
   "              o               ",
   "                              ",
   "xxxxx      xxxxxxx            ",
   "                              ",
   "                              ",
   "      xxx                 x   ",
   "                              ",
   " o                            ",
   "                        o     ",
   "xxx                           ",
   "                        x     ",
   "           xxxxx              ",
   "                              ",
   "                              ",
   "                              ",
   "    x                 x       ",
   "                              ",
   "                              ",
   "                              ",
   "                           *  ",
   "         x           xxxxxxxxx",
   "                              ",
   "x                             ",
   "                              ",
   "                              ",
   "  o            xxxxx          ",
   "xxxxx                         ",
   "                              ",
   "                              ",
   "                           o  ",
   "         x              xxxxxx",
   "                              ",
   "                              ",
   "                              ",
   "                              ",
   "    x                         ",
   "                              ",
   "                              ",
   "                              ",
   "    x  &         x       o    ",
   "    xxxxxxxxxxxxxx     xxxxx  ",
   "                              ",
   "                              ",
   "                              ",
   "                  o           ",
   "               xxxxxxxxx      ",
   "                              ",
   "                              ",
   "       xxxxx                  ",
   "o                             ",
   "x                            *",
   "x                            x",
   "x                             ",
   "xx                            ",
   "xx                            ",
   "xxo                           ",
   "xxx               @           ",
   "xxx          xxxxxxxxxx       ",
   "xxxx       xxxxxxxxxxxxxx     ",
   "xxxx!!!!!xxxxxxxxxxxxxxxxxx!!!",
   "xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!",
   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"],
   //6
  ["                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              ",
   "     xx  xx  xxxx  xx   xx    ",
   "     xx  xx xxxxxx xx   xx    ",
   "     xx  xx xx  xx xx   xx    ",
   "     xxxxxx xx  xx xx   xx    ",
   "      xxxxx xx  xx xx   xx    ",
   "         xx xx  xx xx   xx    ",
   "      xxxxx xxxxxx xxx xxx    ",
   "      xxxxx  xxxx   xxxxx     ",
   "                              ",
   " xx       xx  xx  xxx      xx ",
   " xx       xx  xx  xxxx     xx ",
   " xx   x   xx  xx  xx xx    xx ",
   " xx   x   xx  xx  xx  xx   xx ",
   " xxx  x  xxx  xx  xx   xx  xx ",
   "  xx  x  xx   xx  xx    xx xx ",
   "  xxxxxxxxx   xx  xx     xxxx ",
   "   xxx xxx    xx  xx      xxx ",
   "                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              "]];
  
  



if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
